<?xml version="1.0" encoding="utf-8"?><Database Name="DocumentDB" Class="DocumentDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=DocumentDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DocumentDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Table1s">
    <Type Name="Table1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DocumentType" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DocumentDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Year" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="[File]" Member="File" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>